services:
  - type: web
    name: candidate-shortlisting-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: static
    name: candidate-shortlisting-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html